︠2c28cbae-1390-488d-8bcd-007df1909fa5i︠
%md
This is just a test, please ignore this file.
<br>
<br>
Thank you
︡4144db7a-be75-452d-83d6-a8ed5e8fde01︡{"done":true,"md":"This is just a test, please ignore this file.\n<br>\n<br>\nThank you"}
︠a9a70cd2-d8dd-4c5f-abbd-1813ad7da294s︠
attach("Week2-StarterCode.sage")
︡ef8e3992-dba8-4950-b458-2503257835cd︡{"done":true}︡
︠2357ce92-08cc-4d08-b7c8-97a0388b3b25s︠
X='PRWXASHQGPXCHIPGIHUJCRIXDCXCVPIQXGIWPCSWPHPBDCVHIXIHBPCNXCUPCIRDCKDAJIXDCHIWDJHPCSHDUSDGBPCIPIDBHXCIDLWXRWVDSWPHEJIPBNHIXREDHHXQXAXINUDGCDIXRXCVPCPSJAIHPRIPCSUXVJGXCVDJIXIHEJGEDGIJEIDPQDJIXIHEGXBPGNHRWDDASPNHPRWXASIWXCZHCPIJGPAANDCANDUEAPNQJIBPCNPUDGBDUEAPNRDCIPXCHSXHRXEAXCPGNUPRIDGNDJRPCISDIWXHDGIWPIEJIHDJIDJIHWDLHPRWXASIWPIXIBJHIIWXCZEGPRIXRPAANDGUPXACDLXUIWGDJVWDJIRWXASWDDSPQGPXCWPHCDDEEDHXIXDCXIXHEAPXCIWPIXILXAAPIIPXCPEDHXIXDCDUHIPIJHFJDPHLXIWDJGDGSXCPGNPCXBPAHBPCZCDLHCDILWNPRDLSDVDGAXDCLPHCDIQDGCLXIWPQGPXCDCPEPGLXIWDJGHLWNHJRWPCXBPAHRPCCDIPSSHJQIGPRIDGDQIPXCUGDBQDDZHPCSHRWDDAXCVIWPIEPGPBDJCIEDHXIXDCLWXRWBPCWDASHIDSPNQJIPWJBPCQGPXCXHCDIXCIWPIRAPHHRDCHIPCIANIWGDQQXCVPCSEJAHPIXCVXIGPEXSANUDGBHDEXCXDCH'
︡4e3fe5cc-8abb-437e-80a7-4997c064749b︡{"done":true}︡
︠bb598367-9043-4b14-8496-4f7550bdc845s︠
X
︡8580ed9a-b3d9-4281-a5f8-987b7989b247︡{"stdout":"'PRWXASHQGPXCHIPGIHUJCRIXDCXCVPIQXGIWPCSWPHPBDCVHIXIHBPCNXCUPCIRDCKDAJIXDCHIWDJHPCSHDUSDGBPCIPIDBHXCIDLWXRWVDSWPHEJIPBNHIXREDHHXQXAXINUDGCDIXRXCVPCPSJAIHPRIPCSUXVJGXCVDJIXIHEJGEDGIJEIDPQDJIXIHEGXBPGNHRWDDASPNHPRWXASIWXCZHCPIJGPAANDCANDUEAPNQJIBPCNPUDGBDUEAPNRDCIPXCHSXHRXEAXCPGNUPRIDGNDJRPCISDIWXHDGIWPIEJIHDJIDJIHWDLHPRWXASIWPIXIBJHIIWXCZEGPRIXRPAANDGUPXACDLXUIWGDJVWDJIRWXASWDDSPQGPXCWPHCDDEEDHXIXDCXIXHEAPXCIWPIXILXAAPIIPXCPEDHXIXDCDUHIPIJHFJDPHLXIWDJGDGSXCPGNPCXBPAHBPCZCDLHCDILWNPRDLSDVDGAXDCLPHCDIQDGCLXIWPQGPXCDCPEPGLXIWDJGHLWNHJRWPCXBPAHRPCCDIPSSHJQIGPRIDGDQIPXCUGDBQDDZHPCSHRWDDAXCVIWPIEPGPBDJCIEDHXIXDCLWXRWBPCWDASHIDSPNQJIPWJBPCQGPXCXHCDIXCIWPIRAPHHRDCHIPCIANIWGDQQXCVPCSEJAHPIXCVXIGPEXSANUDGBHDEXCXDCH'\n"}︡{"done":true}︡
︠4301fec3-bd4e-4719-a027-4eab7f3b89dds︠
def autodecrypt(X):
    # X will be a string of ciphertext that was encrypted using a shift cipher.
    # You need to define a string Y that you hope corresponds to the plaintext.
    # Use the outline described in the homework.
    # Your code goes here, no # sign.
    for i in range (0,26):
        freqvec=numpy.dot(getfreq(shift(X,i)),englishfreq)
        if (freqvec > 0.06):
            Y=shift(X,i)
    return Y
︡aee84989-280d-4d14-a3a7-821883446c6b︡{"done":true}︡
︠6c37a41b-f931-4ab3-a21d-be83c7aa9038s︠
autodecrypt(X)
︡51e88807-904e-4fb8-8ff2-7cb6cccbbba1︡{"stdout":"'ACHILDSBRAINSTARTSFUNCTIONINGATBIRTHANDHASAMONGSTITSMANYINFANTCONVOLUTIONSTHOUSANDSOFDORMANTATOMSINTOWHICHGODHASPUTAMYSTICPOSSIBILITYFORNOTICINGANADULTSACTANDFIGURINGOUTITSPURPORTUPTOABOUTITSPRIMARYSCHOOLDAYSACHILDTHINKSNATURALLYONLYOFPLAYBUTMANYAFORMOFPLAYCONTAINSDISCIPLINARYFACTORYOUCANTDOTHISORTHATPUTSOUTOUTSHOWSACHILDTHATITMUSTTHINKPRACTICALLYORFAILNOWIFTHROUGHOUTCHILDHOODABRAINHASNOOPPOSITIONITISPLAINTHATITWILLATTAINAPOSITIONOFSTATUSQUOASWITHOURORDINARYANIMALSMANKNOWSNOTWHYACOWDOGORLIONWASNOTBORNWITHABRAINONAPARWITHOURSWHYSUCHANIMALSCANNOTADDSUBTRACTOROBTAINFROMBOOKSANDSCHOOLINGTHATPARAMOUNTPOSITIONWHICHMANHOLDSTODAYBUTAHUMANBRAINISNOTINTHATCLASSCONSTANTLYTHROBBINGANDPULSATINGITRAPIDLYFORMSOPINIONS'\n"}︡{"done":true}︡
︠300caf3f-d282-4ab8-a815-9f1d55bfded0s︠
pow(3,7,7)
︡bbc8e553-1462-4096-ab38-526ee7906ae1︡{"stdout":"3\n"}︡{"done":true}︡
︠fc09f62e-5ef0-4abc-a54e-fe8e22145677r︠

pow(5,81,9)
︡7eddbb5f-65ed-4773-9ecf-0d43712bc899︡
︠4e9cd16e-9395-4797-a4bb-818c8aa98121︠









